/*!
 * gitbook-plugin-intopic-toc
 * v1.1.1
 * https://github.com/zanfab/gitbook-plugin-intopic-toc#readme
 * (c) 2020 Fabian Zankl
 * MIT license
 */
"use strict";function _typeof(e){return(_typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}var configuration,label;function getAnchorLevel(e){return parseInt(e.tagName.charAt(1),10)}function createNavList(e){var t=document.createElement("ul");return t.classList.add("nav"),t.classList.add("navbar-nav"),t.classList.add("level-".concat(e)),t}function createChildNavList(e,t){var n=createNavList(t);return e.append(n),n}function createNavItem(e,t){var n=document.createElement("a");n.classList.add("nav-link"),n.text=e,n.href=t;var a=document.createElement("li");return a.appendChild(n),a}function getStartingElementIndex(n){for(var e=function(t){var e=n.filter(function(e){return e.tagName.toLowerCase()==="h".concat(t)});if(1<e.length)return{v:n.indexOf(e[0])}},t=1;t<=6;t++){var a=e(t);if("object"===_typeof(a))return a.v}return 0}function buildNavigation(e,t,n,a,o){var r="nested"===n.toLowerCase(),i=document.createElement("nav");i.className="intopic-toc ".concat(n),o&&(i.className+=" collapsed");var c=document.createElement("h3");c.innerText=t,i.appendChild(c);var l={};l[0]=createChildNavList(i,0);for(var s,u=getStartingElementIndex(e),f=getAnchorLevel(e[u]),v=-1,d=u;d<e.length;d++){var p=getAnchorLevel(e[d])-f;if(!(a<=p)){if(-1===v&&(v=p),r){if(p<v)for(var b=v;p<b;b--)delete l[b];l[p]||(l[p]=createChildNavList(s,p))}var h=createNavItem(e[d].textContent,e[d].querySelector(".anchorjs-link").getAttribute("href"));l[r?p:0].appendChild(h),s=h,v=p}}return i}require(["gitbook","jQuery"],function(l,s){anchors.options={placement:"left"},l.events.bind("start",function(e,t){if(configuration=t["intopic-toc"],"object"===_typeof(label=configuration.label)){var n=l.state.innerLanguage;label=n&&Object.prototype.hasOwnProperty.call(label,n)?label[n]:""}var a=s("#book-search-results");new MutationObserver(function(){a.hasClass("open")?s(".intopic-toc").hide():s(".intopic-toc").show()}).observe(a[0],{attributes:!0})}),l.events.bind("page.change",function(){anchors.removeAll(),anchors.add(configuration.selector);var e=(configuration.visible||l.state.page.isTocVisible)&&!1!==l.state.page.isTocVisible,t=configuration.mode,n=Number(configuration.maxDepth),a=Boolean(configuration.isCollapsed),o=Boolean(configuration.isScrollspyActive);if(1<anchors.elements.length&&e){var r=buildNavigation(anchors.elements,label,t,n,a),i=document.body.querySelector(".page-wrapper");if(i.appendChild(r,i.firstChild),o){var c=s(".book-body .body-inner")[0];new Gumshoe(".intopic-toc a",{container:c,navClass:"active",contentClass:"active",nested:!0,offset:c.offsetHeight/2,reflow:!0})}}})});
//# sourceMappingURL=plugin.js.map
